### PR TITLE
Make solution parameter optional and migrate to file-scoped namespace

### PR DESCRIPTION
**Pull request by ITDancer13**

### CODE REVIEW

**Comment by ITDancer13** [comment]
@olsh Please let me know if migration to file-scoped namespaces is okay for you.

**Comment by olsh** [comment]
Hi @ITDancer13 
Thank you for the PR.
This is OK, but only as a separate PR. Reviewing all-in-one PR (especially with large formatting/refactoring) takes much more time.

**Comment by ITDancer13** [comment]
I'll do that

**Review by olsh — CHANGES_REQUESTED** [review]
Please concentrate only on the optional parameter.
Please do not change formatting, syntactic sugar, etc. in the PR.

**Comment by olsh** [comment]
Fixed in #27 
Thank you! 👍🏻

**Pull request closed without merging**
